### ISSUE TITLE
Stopping at 1075MB

### ISSUE THREAD

**Issue by Sewmina7** [abdoxfox/http-ssl-ssh-injector#11]
The connection through injector stops working after around 1075MB of download traffic. Tried changing the proxy command to both NC and Corkscrew, it didnt change anything.

You can reproduce this issue by starting the injector, Downloading a file bigger than 1100MB.

**Comment by abdoxfox** [comment]
i'm about fix it thanks

**Comment by abdoxfox** [comment]
Fixed
