### ISSUE TITLE
Help bro.. 

### ISSUE THREAD

**Issue by AndresLM21** [abdoxfox/http-ssl-ssh-injector#12]
Bro help, I get this error. What I can do?
![Screenshot_20220503-114656](https://user-images.githubusercontent.com/104855776/166502428-98c10d34-8dee-49be-82f0-206ee29631cc.png)

**Comment by abdoxfox** [comment]
Kill the existing connection before restart

**Comment by abdoxfox** [comment]
Custom rom issue was fixing too
