### ISSUE TITLE
Hi is this working on Ubuntu

### ISSUE THREAD

**Issue by avishka40** [abdoxfox/http-ssl-ssh-injector#2]
I have been trying to work with this script 
Getting the following any error like this

![image](https://user-images.githubusercontent.com/29837662/123778741-0ce43d80-d8ef-11eb-8167-0eaaec466ed4.png)

**Comment by abdoxfox** [comment]
you installed required packages?

**Comment by abdoxfox** [comment]
> I have been trying to work with this script
> Getting the following any error like this
> 
> ![image](https://user-images.githubusercontent.com/29837662/123778741-0ce43d80-d8ef-11eb-8167-0eaaec466ed4.png)

try again it was fixed
note you must install python3
