### ISSUE TITLE
Ssh Disconnect

### ISSUE THREAD

**Issue by key1brhni** [abdoxfox/http-ssl-ssh-injector#21]
Hi guys
I want to use this injector in my vps
but when its connect,I lose ssh connection of my vps
Help me please!

**Comment by abdoxfox** [comment]
Reach me at telegram @Abdoxfox_official

**Comment by abdoxfox** [comment]
Why using inside vps 
btw that issue in outside to get help reach me on telegram my. Id : @Abdoxfox_official
