### ISSUE TITLE
ERROR: sudo: ./redsocks/redsocks: command not found

### ISSUE THREAD

**Issue by chmodle** [abdoxfox/http-ssl-ssh-injector#23]
Hi, Got this error. 
" Authenticate to password
CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
sudo: ./redsocks/redsocks: command not found
 KILLING PROCESS...."

what could be the problem?

**Comment by abdoxfox** [comment]
Fixed 👍

**Comment by chmodle** [comment]
chmod: cannot access 'redsocks': No such file or directory
sudo: ./redsocks: command not found
now i get this.

**Comment by abdoxfox** [comment]
Contact me on telegram: @Abdoxfox_official
