### ISSUE TITLE
MacOs problem

### ISSUE THREAD

**Issue by yunusemreyazici** [abdoxfox/http-ssl-ssh-injector#24]
First of all, thank you for sharing your project openly. 
You wrote that it is for linux and android, but I tried it on my mac and got this error. 
How can it be resolved? 
Sni vs tunneling options are very necessary but there is nothing that can do this in macos. application, library, etc.
I would be very happy if you could help. 

Good luck best wishes
![image](https://user-images.githubusercontent.com/102879979/200973755-eaf51863-efe0-45d8-93d0-e087500a1bed.png)

**Comment by abdoxfox** [comment]
@yunusemreyazici dm on telegram to suggest some solutions for your issue
My id @Abdoxfox_official
