### ISSUE TITLE
redsocks issue: debian gnu/linux amd64 (Parrot OS)

### ISSUE THREAD

**Issue by knightfall-cs** [abdoxfox/http-ssl-ssh-injector#25]
Issue:
Authenticate to password
Authentication Comleted
CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
chmod: cannot access 'redsocks': No such file or directory
sudo: ./redsocks: command not found
 KILLING PROCESS....
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
 DONE

I aready installed all packages including redsocks and pip requirments. 

Is there any ways to fix this issue, i think its all about redsocks and also i never used that before. 

Any suggestions?

**Comment by abdoxfox** [comment]
unzip redsocks.zip then get access to redsocks directory and run this command:
make

**Comment by knightfall-cs** [comment]
> unzip redsocks.zip then get access to redsocks directory and run this command: make

Tried but got this error:

**Comment by knightfall-cs** [comment]
> unzip redsocks.zip then get access to redsocks directory and run this command: make

Tried and got this error:

cc -g -O2 -std=c99 -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE -D_GNU_SOURCE -Wall   -c -o parser.o parser.c
In file included from parser.c:29:
utils.h:6:10: fatal error: event.h: No such file or directory
    6 | #include <event.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [<builtin>: parser.o] Error 1

**Comment by knightfall-cs** [comment]
> unzip redsocks.zip then get access to redsocks directory and run this command: make

**Comment by knightfall-cs** [comment]
Tried and got this error:

cc -g -O2 -std=c99 -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE -D_GNU_SOURCE -Wall -c -o parser.o parser.c
In file included from parser.c:29:
utils.h:6:10: fatal error: event.h: No such file or directory
6 | #include <event.h>
| ^~~~~~~~~
compilation terminated.
make: *** [: parser.o] Error 1
