### ISSUE TITLE
iptables issue

### ISSUE THREAD

**Issue by devalt90** [abdoxfox/http-ssl-ssh-injector#27]
# Firstly it's unstable : ( On Debian 11)

# At first connection:

 "Failed to connect ... Try again
 KILLING PROCESS....
 DONE "

I Had to reconnect so I can establish a connection

# Secondly the included redsocks not working even with fix permissions, I had to install it separately ,BUT... :

  " file parsing error at line 35: unknown section <**dnsu2t**>"
 **had to remove it**

# after  establish a connection
 iptables not sharing connection with local network or even any assigned ports from redsocks.conf or proxification.

Local not loading at all .

# Log full of Connection refused

```
1674500389.670143 notice redsocks.c:958 redsocks_relay_connected(...) [192.168.1.39:42214->172.217.19.142:80]: red_is_socket_connected_ok: Connection refused
1674500389.670222 info redsocks.c:686 redsocks_drop_client(...) [192.168.1.39:42214->172.217.19.142:80]: dropping client (R/W), relay (R/W), idle 0.000326s
1674500394.742305 info redsocks.c:1243 redsocks_accept_client(...) [192.168.1.39:58636->172.217.19.142:80]: accepted
1674500394.742869 notice utils.c:223 red_is_socket_connected_ok(...) connect: Connection refused
1674500394.742955 notice redsocks.c:958 redsocks_relay_connected(...) [192.168.1.39:58636->172.217.19.142:80]: red_is_socket_connected_ok: Connection refused
1674500394.742996 info redsocks.c:686 redsocks_drop_client(...) [192.168.1.39:58636->172.217.19.142:80]: dropping client (R/W), relay (R/W), idle 0.000153s
```

**Comment by 3v1ltw1n0x01** [comment]
same for me pull latest commits fixed it + i had to run runvpn.sh as sudo user for it to work probably

**Comment by devalt90** [comment]
> same for me but latest commits fixed it + i had to run runvpn.sh as sudo user for it to work probably

Well I was able to make it work by changing iptable rules but sometime it leeks to real ip, and the most important option networking (http header).
