### ISSUE TITLE
./proxification: line 27: ./redsocks: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by swri** [abdoxfox/http-ssl-ssh-injector#7]
root@swrpc:/home/suwari/Public/http-ssl-ssh-injector# ./runvpn.sh 
Choose Connection Method:
0 - SSH Direct 
1 - PAYLOAD 
2 - SSL 
3 - SSL+PAYLOAD 
Enter choice number : 2
---logs----
[10:05:33] : Waiting for incoming connection to : 127.0.0.1:9092

[10:05:34] : <#> Client 53676 received!
[10:05:34] : [TCP] connected to *********:443
[10:05:35] : [TCP] Handshaked successfully to m.starmakerstudios.com
[10:05:35] : [TCP] Protocol :TLSv1.3
Ciphersuite : TLS_AES_256_GCM_SHA384
Peerprincipal: C=*********, ST=********* , L=v , O=********* , CN=*********
[10:05:35] : kex: algorithm: curve25519-sha256
[10:05:35] : kex: host key algorithm: ecdsa-sha2-nistp256
[10:05:35] : kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: zlib@openssh.com
[10:05:35] : Server host key: *********************************************************
[10:05:35] : Authenticate to password
[10:05:35] : Authentication Comleted
[10:05:35] : CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
./proxification: line 27: ./redsocks: cannot execute binary file: Exec format error

 vpn service stopped
 

reconnect ? [y\n] 

i using ubuntu

**Comment by Aromakelapa** [comment]
Hello Sir, i got this after solving that issue

Authenticate to password
Authentication Comleted
CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
1653811224.745680 notice main.c:165 main(...) redsocks started, conn_max=128
1653811231.678173 info redsocks.c:1243 redsocks_accept_client(...) [192.168.43.178:57230->208.95.112.1:80]: accepted
1653811245.140575 info redsocks.c:1243 redsocks_accept_client(...) [192.168.43.178:39060->104.131.210.97:443]: accepted
1653811245.141131 notice utils.c:223 red_is_socket_connected_ok(...) connect: Connection refused
1653811245.141419 notice redsocks.c:958 redsocks_relay_connected(...) [192.168.43.178:39060->104.131.210.97:443]: red_is_socket_connected_ok: Connection refused
1653811245.141687 info redsocks.c:689 redsocks_drop_client(...) [192.168.43.178:39060->104.131.210.97:443]: dropping client (R/W), relay (R/W), idle 0.000557s

**Comment by abdoxfox** [comment]
Connection refused?

**Comment by Sewmina7** [comment]
Yes. Proxification crashes the proxy. I've found a workaround though. If
you apply proxification while downloading some traffic over proxy. It
works. I've added a line to proxification to start downloading a speedtest
file so now it works like charm. Ik it's not a real solution. But hey it
works

Lmk if I should open a PR

**Comment by abdoxfox** [comment]
Go ahead and opened it

**Comment by Sewmina7** [comment]
@abdoxfox just opened PR

**Comment by Aromakelapa** [comment]
> Connection refused?

yes sir
