### ISSUE TITLE
bind: Address already in use

### ISSUE THREAD

**Issue by WhiteHoot** [abdoxfox/http-ssl-ssh-injector#8]
So i got this error and i don't know which port is already in use.

---Tunneling  starts-----
`1635571718.543088 err dnstc.c:166 dnstc_init_instance(...) bind: Address already in use`

I thought maybe it's using the 1080 port but when i check it using netsat -tulpn it's not being used for anything.

Edit : Okay so i just realized that it's the dnstc that won't initialize, and i checked in the redsocks.conf that it's using 5300, then again when i checked using netstat -tulpn

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name   
udp        0      0 127.0.0.1:5300          0.0.0.0:*                           -          
```

**Comment by Sewmina7** [comment]
This happens because redsocks instance is already running. Use this command to kill it and restart the runvpn.sh

sudo pkill redsocks

**Comment by WhiteHoot** [comment]
> This happens because redsocks instance is already running. Use this command to kill it and restart the runvpn.sh
> 
> sudo pkill redsocks

It worked, thanks.
